### ISSUE TITLE
local use of godello

### ISSUE THREAD

**Issue by moizez102** [alfredbaudisch/Godello#21]
hi! i just wanted to know if there is some way that i can use godello just on my local computer

As far as I understand, no data in godello is currently saved, because you still work in the backend, but I would like to use it simply for personal organization (without the need to log in or internet connectivity, only local use) and save everything on my pc

So I would like to know if this is something that may be added in the future, or simply cannot be due to the way it is done.

In any case, the project is great, keep up the excellent work!

**Comment by alfredbaudisch** [comment]
That could be added, definitely. The backend integration is being done with the adapter pattern in Godot. To store data locally, it would be a matter of creating a SQLite adapter for example, in the same way that I plan to add more server options in the future (by simply writing new adapters).

Thanks for the suggestion!

**Comment by CptFubar** [comment]
Hi, i implemented a local version for Godello using custom resources, meaning there is no further 3rd party software needed to run it. I would gladly do a pull request into a backend_local branch for this project. 

It is completely compatible with the main project but i prefer to pull request into a separate branch so you @alfredbaudisch can asses it's viability to be merged into main.

Here is the link to the [backend_local](https://github.com/CptFubar/Godello/tree/backend_local) branch.

What do you think @alfredbaudisch, would it make sense to have a new branch for a "local" version ?

**Comment by alfredbaudisch** [comment]
> What do you think @alfredbaudisch, would it make sense to have a new branch for a "local" version ?

Yes, please, a Pull Request for this would be :)

From what I can see your branch `backend_local` does not implement the style changes you implemented in the currently open pull request. So it would be better that I first merge the style changes PR and afterwards the backend_local one.

PS: I'll probably review and merge everything next week.

**Comment by CptFubar** [comment]
I don't know when you have had a chance to look at backend_local branch but i branched it after the style changes were applied.
Since the PR #22 was successfully merged, i too merged my local branch into my local master to deal with the conflicts. 
The only conflicts were just the error handling messages that i resolved by using your implementation.

Now i have added the new PR #23 that shows no conflicts and have a working locally stored backend through the use of custom resources.

**Comment by alfredbaudisch** [comment]
Closing this, since there's now a local usage implementation of Godello in the branch: https://github.com/alfredbaudisch/Godello/tree/local-backend (thanks @CptFubar!).

But notice that there's still a breaking bug there: #28.
