### ISSUE TITLE
Do you intend to implement the power ups that Trello has?

### ISSUE THREAD

**Issue by Malkverbena** [alfredbaudisch/Godello#25]
Trello has some powerups that are paid. Will you implement them?

**Comment by alfredbaudisch** [comment]
There's a very big amount of features not implemented from Trello. The idea of this project is just the basic UI core, not all the features (for example, Godello does not have file/image attachments). So it's very unlikely that will implement the powerups. Of course, external contributors are always welcome to implement anything, considering the project is open-source :)
