### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by MeBadDev** [alfredbaudisch/Godello#27]
looks like the last commit is 11 months ago

**Comment by alfredbaudisch** [comment]
The Trello-like interface is already fully implemented (and quite complete and complex). But the other things are unlikely that I will finish, I left a note in the [Roadmap](https://github.com/alfredbaudisch/Godello#roadmap-%EF%B8%8F).

Anyway, today a big new contribution has been made, it's available in the [local-backend branch](https://github.com/alfredbaudisch/Godello/tree/local-backend). It requires #28 to be fixed before merged into master.
